# Generated by Django 3.1.3 on 2020-12-29 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Category name')),
                ('slug', models.SlugField(max_length=55, unique=True, verbose_name='Category url')),
                ('description', models.TextField(blank=True, verbose_name='Category description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Curt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Delivery title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Delivery price')),
                ('description', models.TextField(blank=True, verbose_name='Delivery description')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone num')),
                ('price', models.PositiveSmallIntegerField(null=True, verbose_name='price')),
                ('address', models.TextField(blank=True, verbose_name='Delivery address')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Status name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.URLField(verbose_name='url from store')),
                ('title', models.CharField(max_length=255, verbose_name='Product name')),
                ('photo', models.ImageField(upload_to='product_poster/', verbose_name='General photo')),
                ('description', models.TextField(blank=True, verbose_name='Product description')),
                ('sizes', models.CharField(blank=True, max_length=100, verbose_name='Product sizes')),
                ('colors', models.CharField(blank=True, max_length=50, verbose_name='Product colors')),
                ('origin_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Original product price')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='My product price')),
                ('slug', models.SlugField(max_length=55, unique=True, verbose_name='Product url')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Publish or NOT')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Quantity')),
                ('category', models.ManyToManyField(to='shop.Category', verbose_name='Product categories')),
                ('delivery', models.ManyToManyField(to='shop.Delivery', verbose_name='Delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500, verbose_name='Review')),
                ('photo', models.ImageField(upload_to='product_reviews/', verbose_name='Reviews photo')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Photo title')),
                ('description', models.TextField(blank=True, verbose_name='Photo description')),
                ('image', models.ImageField(upload_to='product_photos', verbose_name='Product photo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Products')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5, verbose_name='Product size')),
                ('price', models.PositiveSmallIntegerField(verbose_name='price')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.OrderProduct', verbose_name='Order products'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.orderstatus', verbose_name='order status'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField(null=True, verbose_name='Phone number')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('address2', models.CharField(blank=True, max_length=50, verbose_name='Address line 2')),
                ('zipcode', models.CharField(max_length=8, verbose_name='Post index')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('country', models.CharField(max_length=50, verbose_name='User county')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='CurtProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=4, verbose_name='Product size')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('curt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.curt', verbose_name='cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='product')),
            ],
        ),
        migrations.AddField(
            model_name='curt',
            name='cart_product',
            field=models.ManyToManyField(blank=True, to='shop.CurtProduct', verbose_name='product id'),
        ),
        migrations.AddField(
            model_name='curt',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
