# Generated by Django 3.1.3 on 2020-12-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201229_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AlterField(
            model_name='product',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Draft'),
        ),
    ]
