# Generated by Django 3.1.3 on 2021-01-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201231_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(max_length=100, verbose_name='Product sizes'),
        ),
    ]
