# Generated by Django 3.1.3 on 2021-01-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210107_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Original product price'),
        ),
    ]
