# Generated by Django 3.1.3 on 2021-01-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_product_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Weight'),
        ),
    ]
