# Generated by Django 3.1.3 on 2021-01-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210108_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='', max_length=17, verbose_name='Phone number'),
        ),
    ]
