# Generated by Django 3.1.3 on 2021-01-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='areas',
            field=models.CharField(blank=True, max_length=25, verbose_name='Delivery areas'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='max_weight',
            field=models.PositiveIntegerField(default=0, verbose_name='max_weight'),
        ),
    ]
